### ISSUE TITLE
Cannot delete namespace permission from scabbard CLI

### ISSUE THREAD

**Issue by rohitmp** [splintercommunity/splinter#5]
delete a Sabre namespace permission has a conflict clause with "contract" argument.(contract_name)
Hence CANT specify the contract name from cli, while deleting the perm.

But the DeleteNamespaceRegistryPermissionActionBuilder also has a validation that requires contract_name
ActionBuildError::MissingField("'contract_name' field is required".to_string())

SO if we dont specify the contract name, the validation fails, and perm is not deleted.

We need to remove the conflict clause from the CLI subcommand

**Comment by vaporos** [comment]
Please add a sign-off to satisfy the DCO check. You can add this with "git commit -s --amend" and then re-pushing the branch.
